import { Header } from "@/components/layout/header";
import Footer from "@/components/Footer";

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-background">
      <main className="w-full mx-auto relative h-full overflow-x-hidden">
        <div className="md:w-full">
          <section className="flex flex-col min-h-screen w-full pt-4">
            <div className="lg:px-0 px-4">
              <h1 className="text-4xl lg:text-5xl font-[600] text-left tracking-tighter text-foreground mb-4">
                Privacy Policy
              </h1>

              <div className="prose prose-invert max-w-none">
                <p className="text-sm lg:text-lg text-muted-foreground mb-6">
                  Last Updated: November 25, 2025
                </p>

                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Welcome to My Outfit ("we", "us", "our").
                </p>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Your privacy is important to us. This Privacy Policy explains
                  how we collect, use, store, share, and protect your personal
                  information when you use our platform, mobile application, and
                  related services (collectively, the "Services").
                </p>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  By accessing or using My Outfit, you agree to this Privacy
                  Policy and our{" "}
                  <a href="/terms" className="text-[#0095f6] hover:underline">
                    Terms of Service
                  </a>
                  . If you do not agree, please discontinue use of our Services
                  immediately.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  1. Overview of Our Commitment
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  At My Outfit, we are committed to maintaining the trust and
                  confidence of our users. We handle all personal data with
                  care, transparency, and respect, applying international
                  privacy principles such as:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>Lawfulness, fairness, and transparency</li>
                  <li>Purpose limitation</li>
                  <li>Data minimization</li>
                  <li>Accuracy</li>
                  <li>Storage limitation</li>
                  <li>Integrity and confidentiality</li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Our goal is to allow users to freely create, try on, and share
                  outfits while retaining full control over their personal data.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  2. Information We Collect
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  We collect different types of information to provide and
                  improve our Services. This includes:
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  2.1. Information You Provide
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Account Data:</strong> When you create an account,
                    we collect your name, email address, password, and optional
                    username or display name.
                  </li>
                  <li>
                    <strong>Profile Information:</strong> Includes your avatar
                    or photo, preferences, body measurements, and other optional
                    data to improve AI try-on accuracy.
                  </li>
                  <li>
                    <strong>Outfit Data:</strong> Includes outfits you create,
                    save, or share (e.g., images generated by AI, item
                    selections, outfit descriptions, tags, likes, and comments).
                  </li>
                  <li>
                    <strong>Communication Data:</strong> Messages, feedback, or
                    inquiries you send through support channels.
                  </li>
                  <li>
                    <strong>Payment Data:</strong> If you purchase packages or
                    subscriptions, we collect limited payment details via
                    third-party processors (e.g., Polar, Stripe). My Outfit
                    never stores full credit card numbers.
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  2.2. Information Collected Automatically
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Usage Data:</strong> Information about your
                    interactions with our Services (e.g., pages viewed, time
                    spent, actions taken).
                  </li>
                  <li>
                    <strong>Device & Log Data:</strong> Includes IP address,
                    browser type, device type, OS, date/time of access, and app
                    version.
                  </li>
                  <li>
                    <strong>Cookies & Tracking Technologies:</strong> We use
                    cookies and similar technologies to enhance user experience,
                    save preferences, and analyze usage.
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  2.3. Information from Third Parties
                </h3>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  We may receive limited information from third-party services
                  integrated with My Outfit, including:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Authentication Providers</strong> (e.g., Google,
                    Apple, or other OAuth services)
                  </li>
                  <li>
                    <strong>Product Catalog Partners</strong> (e.g., StockX, or
                    brand APIs) — product metadata such as item names, colors,
                    materials, and pricing.
                  </li>
                  <li>
                    <strong>Payment Processors</strong> (e.g., Polar, Stripe) —
                    transaction confirmation and status data.
                  </li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  All such information is processed according to this Privacy
                  Policy and the privacy terms of the respective third party.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  3. How We Use Your Information
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  We use your data to operate, personalize, and improve My
                  Outfit, including:
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Account Management
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>To register and authenticate users.</li>
                  <li>To manage subscriptions and try-on credits.</li>
                  <li>To provide customer support and resolve issues.</li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Service Operation
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>To generate and render outfits using AI technology.</li>
                  <li>To store and display saved outfits on your profile.</li>
                  <li>
                    To enable public or private sharing of outfits depending on
                    user settings.
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Personalization
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>To tailor recommendations and outfit suggestions.</li>
                  <li>
                    To improve AI try-on accuracy based on prior interactions
                    and preferences.
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Communication
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    To send service-related updates, notifications, or support
                    messages.
                  </li>
                  <li>
                    To provide marketing content or feature updates (with your
                    consent).
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Analytics & Improvements
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    To monitor app performance, detect bugs, and optimize user
                    experience.
                  </li>
                  <li>
                    To conduct aggregated, anonymized statistical analysis.
                  </li>
                </ul>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Legal & Security
                </h3>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>To prevent fraud, abuse, or unauthorized access.</li>
                  <li>
                    To comply with applicable laws, regulations, and court
                    orders.
                  </li>
                </ul>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  4. Public Visibility and User-Generated Content
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  My Outfit allows users to create and share outfits publicly or
                  privately. Depending on your privacy settings:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Public Outfits:</strong> May be visible to other
                    users, including your username, avatar, and outfit details.
                  </li>
                  <li>
                    <strong>Current Outfit:</strong> By default, your current
                    outfit may be visible in your public profile, unless you
                    change your visibility preferences.
                  </li>
                  <li>
                    <strong>Saved Outfits:</strong> Are private by default and
                    only shared when you choose to publish them.
                  </li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  You remain the owner of all content you create, but by posting
                  publicly you grant My Outfit a non-exclusive license to
                  display that content within the platform for sharing and
                  discovery purposes.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  5. Legal Basis for Processing (GDPR Compliance)
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  For users in the European Economic Area (EEA), we process your
                  data under the following lawful bases:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Consent</strong> – For marketing communications or
                    optional features.
                  </li>
                  <li>
                    <strong>Contractual necessity</strong> – To provide the
                    Services you request.
                  </li>
                  <li>
                    <strong>Legitimate interest</strong> – For analytics,
                    product improvement, and fraud prevention.
                  </li>
                  <li>
                    <strong>Legal obligation</strong> – When required by law or
                    legal processes.
                  </li>
                </ul>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  6. Data Sharing and Disclosure
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  We do not sell or rent your personal data. We may share
                  information only with:
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Service Providers
                </h3>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Cloud storage, analytics, AI generation services, and payment
                  processors bound by confidentiality agreements.
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Legal Authorities
                </h3>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  When required by law, court order, or governmental request.
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Business Transfers
                </h3>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  In case of merger, acquisition, or sale, data may be
                  transferred to the successor entity under the same privacy
                  standards.
                </p>

                <h3 className="text-xl font-semibold text-foreground mb-3">
                  Public Data
                </h3>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Content explicitly shared by users publicly may appear in
                  search results, feeds, or discovery pages.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  7. Data Retention
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  We retain personal data only as long as necessary for the
                  purposes described:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    <strong>Account data:</strong> Retained while the account is
                    active.
                  </li>
                  <li>
                    <strong>Outfits and AI images:</strong> Retained until
                    deleted by the user.
                  </li>
                  <li>
                    <strong>Logs and analytics:</strong> Retained for up to 12
                    months for performance and debugging.
                  </li>
                  <li>
                    <strong>Payment records:</strong> Retained per legal and tax
                    obligations.
                  </li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Upon account deletion, most data is erased within 30 days,
                  except where required for compliance or dispute resolution.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  8. Your Rights
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  Depending on your location, you have the right to:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>Access your personal data.</li>
                  <li>Request correction of inaccurate information.</li>
                  <li>Request deletion ("Right to be forgotten").</li>
                  <li>Restrict or object to certain processing.</li>
                  <li>Request data portability (GDPR Art. 20).</li>
                  <li>Withdraw consent at any time.</li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  You can exercise these rights via your account settings or by
                  contacting us at{" "}
                  <a
                    href="mailto:contact@myout.fit"
                    className="text-[#0095f6] hover:underline"
                  >
                    contact@myout.fit
                  </a>
                  .
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  9. Data Security
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  We implement industry-standard security measures to protect
                  your data, including:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>End-to-end encryption of sensitive communications.</li>
                  <li>
                    Token-based authentication and secure session handling.
                  </li>
                  <li>
                    Regular security audits and vulnerability assessments.
                  </li>
                  <li>Access control based on least-privilege principles.</li>
                </ul>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Despite these measures, no system is completely secure. Users
                  are encouraged to use strong passwords and log out from shared
                  devices.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  10. AI Processing and Image Data
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  Our AI services process uploaded photos to generate try-on
                  visuals. Key principles:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    Images are processed securely and may be temporarily stored
                    for rendering.
                  </li>
                  <li>
                    We do not use your photos for model training without
                    explicit consent.
                  </li>
                  <li>
                    You may delete any generated outfit or image at any time.
                  </li>
                  <li>
                    We use anonymized metadata (e.g., aspect ratios, pose
                    coordinates) to improve accuracy.
                  </li>
                </ul>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  11. Children's Privacy
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Our Services are not intended for users under 13 years of age
                  (or equivalent age as defined by local law). We do not
                  knowingly collect data from minors. If we discover such data,
                  we will delete it promptly.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  12. International Data Transfers
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-4">
                  We may transfer and process data in countries outside your
                  jurisdiction, such as the United States or the European Union.
                  In such cases, we ensure appropriate safeguards through:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>Standard Contractual Clauses (SCCs)</li>
                  <li>Data Processing Agreements (DPAs)</li>
                  <li>GDPR-compliant frameworks</li>
                </ul>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  13. Third-Party Services and Links
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  Our Services may include links or integrations with
                  third-party services (e.g., brand APIs, AI providers, payment
                  processors). We are not responsible for their privacy
                  practices, and we encourage users to review their respective
                  policies.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  14. Changes to This Privacy Policy
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  We may update this Privacy Policy from time to time. Updates
                  will be notified via email or app notification. The "Last
                  Updated" date reflects the latest revision. Continued use of
                  My Outfit after updates constitutes acceptance of the new
                  policy.
                </p>

                <h2 className="text-2xl font-semibold text-foreground mb-4">
                  15. Contact
                </h2>
                <p className="text-sm lg:text-base text-muted-foreground mb-6">
                  If you have questions about this Privacy Policy, you can
                  contact us through:
                </p>
                <ul className="list-disc list-inside text-sm lg:text-base text-muted-foreground mb-6 space-y-2">
                  <li>
                    Email:{" "}
                    <a
                      href="mailto:contact@myout.fit"
                      className="text-[#0095f6] hover:underline"
                    >
                      contact@myout.fit
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
